POST http://localhost:3333/events
Content-Type: application/json

{
 "title": "Classiaascos",
 "details": "Amiasastoso",
 "maximumAttendeaes": 29168,
 "slug": "ingresdaso"
} 


###
POST http://localhost:3333/events/fdc06052-5633-4c66-a380-4b32ed2439e9/attendaes
Content-Type: application/json

{ 
 "name": "bruna",
 "email": "brssaunas@gmail.com"
}

###
GET  http://localhost:3333/events/fdc06052-5633-4c66-a380-4b32ed2439e9


###
GET  http://localhost:3333/attendaes/3/badge

###
GET  http://localhost:3333/attendaes/3/check-in 
###
GET  http://localhost:3333/events/fdc06052-5633-4c66-a380-4b32ed2439e9/attendees?

###
GET  http://localhost:3333/events/fdc06052-5633-4c66-a380-4b32ed2439e9/attendees?query=anderson